### ISSUE TITLE
下载Res时出错

### ISSUE THREAD

**Issue by mobius007** [letheriver2007/Firefly-Launcher#17]
下载LunarCore的Res时显示如下错误该如何解决
![屏幕截图 2024-05-16 130452](https://github.com/letheriver2007/Firefly-Launcher/assets/107481631/4a250a77-6e7c-4a1d-890d-f39163b3af01)

**Comment by letheriver2007** [comment]
ConfigSummonUnit 于2.2被删除，将在下个发行版更新Res合并引发的路径错误
