### ISSUE TITLE
关于启动器的二次开发和派发

### ISSUE THREAD

**Issue by AstroAir** [letheriver2007/Firefly-Launcher#4]
您好，我在Github上看到了您编写的启动器，与我最近正在写的部分相似，我希望能够实现一个天文软件的相关的启动器，不知道可否使用您的代码，我会在根目录标明使用了您的代码，并且会使用GPL3进行开源。希望能够获得您的许可。

PS：第一次咨询这样的问题，不知道该怎么说，不好意思QWQ

**Comment by letheriver2007** [comment]
你好，很高兴我的仓库对你有帮助，你可以在你的代码中使用本仓库的任何资源（其实你自己偷偷用我也不会知道）。
这是我的第一个此类项目，组件库基于[PyQt-Fluent-Widgets](https://github.com/zhiyiYo/PyQt-Fluent-Widgets)，同样使用GPL3协议，希望你可以注明组件来源。

**Comment by letheriver2007** [comment]
> 您好，我在Github上看到了您编写的启动器，与我最近正在写的部分相似，我希望能够实现一个天文软件的相关的启动器，不知道可否使用您的代码，我会在根目录标明使用了您的代码，并且会使用GPL3进行开源。希望能够获得您的许可。
> 
> PS：第一次咨询这样的问题，不知道该怎么说，不好意思QWQ

你好，很高兴我的仓库对你有帮助，你可以在你的代码中使用本仓库的任何资源（其实你自己偷偷用我也不会知道）。
这是我的第一个此类项目，组件库基于[PyQt-Fluent-Widgets](https://github.com/zhiyiYo/PyQt-Fluent-Widgets)，同样使用GPL3协议，希望你可以注明组件来源。

**Comment by letheriver2007** [comment]
> 您好，我在Github上看到了您编写的启动器，与我最近正在写的部分相似，我希望能够实现一个天文软件的相关的启动器，不知道可否使用您的代码，我会在根目录标明使用了您的代码，并且会使用GPL3进行开源。希望能够获得您的许可。
> 
> PS：第一次咨询这样的问题，不知道该怎么说，不好意思QWQ

你好，很高兴我的仓库对你有帮助，你可以在你的代码中使用本仓库的任何资源（其实你自己偷偷用我也不会知道）。
这是我的第一个此类项目，组件库基于[PyQt-Fluent-Widgets](https://github.com/zhiyiYo/PyQt-Fluent-Widgets)，同样使用GPL3协议，希望你可以注明组件来源。

**Comment by AstroAir** [comment]
非常感谢，我会将我的代码开源出来，并且如果可以的话，我希望能够为这个启动器做出一些贡献
